version: '3'
services:
  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  backend:
    build: 
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"